#spring.application.name=journalApp
#spring.mongodb.uri=mongodb+srv://raiyannodoliya97_db_user:WuDrLUBoKYhajBgJ@cluster0.xcyjctj.mongodb.net/?appName=Cluster0
#spring.mongodb.database=journaldb
#spring.data.mongodb.auto-index-creation=true
#server.port=8080
#
